boto3

diff --git a/.github/workflows/db_migration.yml b/.github/workflows/db_migration.yml
--- a/.github/workflows/db_migration.yml
+++ b/.github/workflows/db_migration.yml
@@ -28,4 +28,49 @@ jobs:
           aws s3 cp init.py s3://499989195637-devops-scripts/init.py 
           echo "✅ Files Uploaded to bucket.."
 
+jobs:
+  init-db:
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v4
+        with:
+          repository: Anujkumar-9/Banking-APP
+          ref: m  id: init
+        run: |
+          CMD_ID=$(aws ssm send-command \
+            --targets "Key=tag:App,Values=flask" \
+            --document-name "AWS-RunShellScript" \
+            --parameters '{"commands":[
+              "aws s3 cp s3://720800607391-devops-scripts/init.sql",  
+              "aws s3 cp s3://720800607391-devops-scripts/init.py /tmp/init.py",
+              "python3 /tmp/init.py || exit 1",
+              "rm /tmp/init.py"
+            ]}' \
+            --query 'Command.CommandId' \
+            --output text \
+            --region us-east-1)
+          echo "cmd_id=$CMD_ID" >> $GITHUB_OUTPUT
+
+      - name: Show Results
+        run: |
+          sleep 30
+
+          aws ssm list-command-invocations \
+            --command-id "${{ steps.init.outputs.cmd_id }}" \
+            --details \
+            --region us-east-1 \
+            --output text
+
+          FAILED=$(aws ssm list-command-invocations \
+            --command-id "${{ steps.init.outputs.cmd_id }}" \
+            --query "length(CommandInvocations[?Status=='Failed'])" \
+            --output text \
+            --region us-east-1)
+
+          [ "$FAILED" -gt 0 ] && \
+            echo "::error::Database Creation Failed $FAILED instance(s)!" && \
+            exit 1
+
+          echo "✅ Database Created Successfully"
+
           
