Fix smoke test workflow

diff --git a/.github/workflows/smoke_test.yml b/.github/workflows/smoke_test.yml
--- a/.github/workflows/smoke_test.yml
+++ b/.github/workflows/smoke_test.yml
@@ -1,4 +1,4 @@
-name : Smoke Testing For Infra and Networking
+name: Smoke Testing For Infra and Networking
 
 on:
   workflow_call:
@@ -6,40 +6,44 @@ on:
 permissions:
   id-token: write
   contents: read
-  
+
 jobs:
   smoke:
     runs-on: ubuntu-latest
+
     steps:
-      - uses: aws-actions/configure-aws-credentials@v4
+      - uses: actions/checkout@v4
+
+      - name: Configure AWS
+        uses: aws-actions/configure-aws-credentials@v4
         with:
-          role-to-assume: arn:aws:iam::720800607391:role/github-action-deploy-role
+          role-to-assume: arn:aws:iam::499989195637:role/git-action-deploy-role
           aws-region: us-east-1
 
-      - name: All files
-        run: |
-          ls -la
+      - name: List repository files
+        run: ls -la
 
-      - name: Upload smoke_test.py on AWS
+      - name: Upload smoke_test.py to S3
         run: |
           aws s3 cp smoke_test.py \
-          s3://720800607391-devops-scripts/smoke_test.py \
-          --region us-east-1
+            s3://499989195637-devops-scripts/smoke_test.py \
+            --region us-east-1
 
       - name: Run Smoke Test on Fleet
         id: smoke
         run: |
           CMD_ID=$(aws ssm send-command \
-          --targets "Key=tag:App,Values=flask" \
-          --document-name "AWS-RunShellScript" \
-          --parameters '{"commands":[
-            "aws s3 cp s3://720800607391-devops-scripts/smoke_test.py /tmpr/smoke_test.py",
-            "python3 /tmpr/smoke_test.py",
-            "rm /tmpr/smoke_test.py"
-            ]}'\
-
-            --query 'Command.CommandId'\
-            --output text
+            --targets "Key=tag:App,Values=flask" \
+            --document-name "AWS-RunShellScript" \
+            --parameters '{
+              "commands":[
+                "aws s3 cp s3://499989195637-devops-scripts/smoke_test.py /tmp/smoke_test.py",
+                "python3 /tmp/smoke_test.py",
+                "rm -f /tmp/smoke_test.py"
+              ]
+            }' \
+            --query 'Command.CommandId' \
+            --output text \
             --region us-east-1)
 
           echo "cmd_id=$CMD_ID" >> $GITHUB_OUTPUT
@@ -49,21 +53,22 @@ jobs:
           sleep 30
 
           aws ssm list-command-invocations \
-          --command-id "${{ steps.smoke.outputs.cmd_id }}" \
-          --details \
-          --region us-east-1
-          --output text
+            --command-id "${{ steps.smoke.outputs.cmd_id }}" \
+            --details \
+            --query "CommandInvocations[*].{Instance:InstanceId,Status:Status,Output:CommandPlugins[0].Output}" \
+            --output table \
+            --region us-east-1
 
           FAILED=$(aws ssm list-command-invocations \
-           --command-id "${{ steps.smoke.outputs.cmd_id }}" \
-           --query "length(CommandInvocations[?Status=='Failed'])" \
-           --output text \
-           --region us-east-1
-          )
+            --command-id "${{ steps.smoke.outputs.cmd_id }}" \
+            --query "length(CommandInvocations[?Status=='Failed'])" \
+            --output text \
+            --region us-east-1)
 
-          [ "$FAILED" -gt 0 ] && \
-          echo "::error::Smoke Test  $FAILED instances" && \
-          exit 1
+          if [ "$FAILED" -gt 0 ]; then
+            echo "::error::$FAILED instance(s) failed the smoke test."
+            exit 1
+          fi
 
           echo "Smoke Test Passed ✅"
           
